require: 
  - rubocop-packaging
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - 'filterameter.gemspec'
    - 'gemfiles/*.gemfile'
    - 'Rakefile'
    - 'spec/dummy/bin/**/*'
    - 'spec/dummy/db/schema.rb'
    - 'spec/dummy/config.ru'
    - 'spec/dummy/config/**/*'
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Guardfile'
  AllowedMethods:
    - 'class_methods'
Layout/LineLength:
  Max: 120
Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/dummy/db/**/*'
Style/HashSyntax:
  EnforcedShorthandSyntax: either
RSpec/MultipleExpectations:
  Exclude:
    - 'spec/requests/*'
