require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'filterameter.gemspec'
    - 'gemfiles/*.gemfile'
    - 'Rakefile'
    - 'spec/dummy/bin/**/*'
    - 'spec/dummy/db/schema.rb'
    - 'spec/dummy/config.ru'
    - 'spec/dummy/config/**/*'
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Guardfile'
Layout/LineLength:
  Max: 120
Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/dummy/db/**/*'
