AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'filterameter.gemspec'
    - 'Rakefile'
    - 'spec/dummy/bin/**/*'
    - 'spec/dummy/db/schema.rb'
    - 'spec/dummy/config.ru'
    - 'spec/dummy/config/**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Guardfile'
Metrics/LineLength:
  Max: 120
Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/dummy/db/**/*'
