# yaml-language-server: $schema=https://www.rubyschema.org/rails/database.json

%YAML 1.1
---
default: &default
  adapter: sqlite3
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3
