default: &default
  adapter: postgresql
  encoding: unicode
  user: filterameter
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: filterameter

test:
  <<: *default
  database: filterameter_test
