name: 'RSpec'
on:
  - push

jobs:
  tests:
    name: 'RSpec'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.0', '3.1']
        gemfile:
          - rails_6
          - rails_6_1
          - rails_7
        exclude:
          - ruby: '3.1'
            gemfile: 'rails_6'
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      BUNDLE_PATH_RELATIVE_TO_CWD: true
    services:
      db:
        image: postgres:11
        env:
          POSTGRES_USER: filterameter
          POSTGRES_DB: filterameter_test
          POSTGRES_PASSWORD: r!teoqA2bA
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@master

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: default
          bundler-cache: true

      - name: 'RSpec'
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://filterameter:@localhost:5432/filterameter_test
          POSTGRES_USER: filteramter
          POSTGRES_PASSWORD: r!teoqA2bA
        run: |
          bundle exec rails db:test:load
          bundle exec rspec --format progress
